version: '3.9'

services:
  celery:
    container_name: celery
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: celery -A tasks.celery worker -l ${CELERY_LOGLEVEL} -c 2 -n worker@ergopad -Q ${CELERY_QUEUE} # -f logs/celery.log #--without-heartbeat --without-gossip --without-mingle
    networks:
      - ergopad-data_net
      - ergopad-node_net

  celerybeat:
    container_name: celerybeat
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: celery -A beat.celery beat -l ${CELERY_LOGLEVEL} # -f logs/celerybeat.log
    networks:
      - ergopad-data_net

  pgmaint:
    container_name: pgmaint
    image: postgres:alpine
    env_file: ${ENV_FILE}
    working_dir: /app
    environment:
      - BASEDIR=/backups
      - DBLIST=ergopad alpha hello
      - DUMPPREFIX=prod
    volumes:
      - /backups/pgmaint:/backups
      - ./periodic/daily:/etc/periodic/daily/:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    command: tail /dev/null -f
    networks:
      - ergopad-data_net

  celeryui:
    container_name: celeryui
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    volumes: 
      - ./app:/app
    profiles: 
      - disabled
    command: uvicorn main:app --host 0.0.0.0 --reload
    networks:
      - ergopad-data_net

networks:
  ergopad-data_net:
    external: true
  ergopad-node_net:
    external: true
